[package]
name = "di-rs"
version = "0.1.0"
authors = ["Alec Keen <aleckeen@tutanota.com>"]
license = "MIT"
edition = "2018"
description = "Small Rust library to get cache/config/data paths for Linux."

[dependencies]
