[package]
name = "di-rs"
version = "0.1.0"
authors = ["Alec Keen <aleckeen@tutanota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "di-rs-test"
path = "test/main.rs"